# In the backend as this is 10kb of text that is not needed often at all
# This is all of google webfonts + Tisa
FONTS = sorted([
  "Open Sans","Lakki Reddy","Taviraj","Roboto","Slabo 27px","Lato","Reem Kufi",
  "Oswald","Roboto Condensed","Source Sans Pro","Montserrat","Raleway",
  "Uncial Antiqua","PT Sans","Lora","Roboto Slab","Open Sans Condensed",
  "Droid Sans","Ubuntu","Yrsa","Droid Serif","Merriweather","Arimo",
  "Noto Sans","PT Sans Narrow","Titillium Web","PT Serif","Playfair Display",
  "Bungee Inline","Indie Flower","Muli","Fjalla One","Inconsolata","Dosis",
  "Bitter","Oxygen","Cabin","Dekko","Hind","Noto Serif","Arvo","Lobster",
  "Passion One","Yanone Kaffeesatz","Poiret One","Nunito","Poppins","Exo 2",
  "Alegreya Sans","Hind Guntur","Merriweather Sans","Abel","Josefin Sans",
  "Bree Serif","Libre Baskerville","Fira Sans","Ubuntu Condensed","Asap",
  "Archivo Narrow","Pacifico","Crimson Text","Anton","Risque","Catamaran",
  "Candal","Varela Round","Quicksand","Shadows Into Light","Signika",
  "Francois One","Vollkorn","Questrial","Karla","Cuprum","Exo","Arima Madurai",
  "Maven Pro","PT Sans Caption","Denk One","Orbitron","Play","Dancing Script",
  "Abril Fatface","Rokkitt","Alegreya","Work Sans","Rubik","Roboto Mono",
  "Patua One","Pathway Gothic One","Trirong","Prompt","EB Garamond","Eczar",
  "Tillana","Rasa","Righteous","Amatic SC","Crete Round","Neuton","Vesper Libre",
  "Space Mono","Monda","Montez","Yellowtail","Amiko","Lalezar","BioRhyme","Farsan",
  "Noticia Text","Hammersmith One","Kaushan Script","Libre Franklin","News Cycle",
  "Rubik One","Bungee","Suez One","Bungee Shade","Shrikhand","Rakkas","Mogra",
  "Yatra One","Gloria Hallelujah","Permanent Marker","Ropa Sans","Sanchez",
  "Josefin Slab","Lobster Two","Comfortaa","Black Ops One","Cutive","Trocchi",
  "Concert One","Kavoon","Ewert","Fruktur","Scope One","Architects Daughter",
  "Chewy","Cairo","Asul","Quattrocento Sans","Acme","Cormorant Garamond",
  "Cormorant Infant","Cormorant","Russo One","Copse","Monoton","Gravitas One",
  "Creepster","Alike Angular","Domine","Pontano Sans","ABeeZee","Cinzel",
  "Cantarell","Gudea","Source Code Pro","Istok Web","BenchNine","Courgette",
  "Old Standard TT","Athiti","Pridi","Maitree","Mitr","Proza Libre",
  "Covered By Your Grace","Economica","Changa","Cormorant SC","Mukta Vaani",
  "Cormorant Unicase","Armata","Satisfy","Quattrocento","Lemonada","Bangers",
  "Coming Soon","Archivo Black","Hind Vadodara","Hind Siliguri","Heebo",
  "Frank Ruhl Libre","Cormorant Upright","Hind Madurai","Atma","David Libre",
  "Vidaloka","Alfa Slab One","Tinos","Mirza","Sigmar One","Ruda","Fredoka One",
  "Handlee","Baloo","Baloo Thambi","Baloo Bhai","Coiny","Baloo Da","Chathura",
  "BioRhyme Expanded","Sintony","Varela","Amatica SC","Mada","Cabin Condensed",
  "Kreon","Arapey","Jomhuria","Katibeh","Bungee Hairline","Pavanam",
  "Kumar One Outline","Bungee Outline","Kumar One","Droid Sans Mono",
  "Didact Gothic","Playfair Display SC","Cardo","Source Serif Pro","Playball",
  "Great Vibes","Harmattan","Oleo Script","Antic Slab","Bevan","Volkhov",
  "Cookie","Shadows Into Light Two","Rock Salt","Philosopher","Audiowide",
  "Kanit","Poller One","Boogaloo","Teko","Luckiest Guy","Tangerine","Changa One",
  "Days One","Ek Mukta","Pattaya","Actor","Rambla","Glegoo","Bad Script",
  "El Messiri","Special Elite","Amiri","Sorts Mill Goudy","Nobile","Khula",
  "Antic","Damion","Paytone One","Patrick Hand","Rajdhani","Signika Negative",
  "Gentium Book Basic","Alice","Scada","Marck Script","Homenaje","Meera Inimai",
  "Aldrich","Homemade Apple","Alegreya Sans SC","Squada One","Molengo","Khand",
  "Amaranth","Alex Brush","Convergence","Cantata One","Sacramento","Jura",
  "Nova Oval","Voltaire","Fauna One","Average Sans","Ultra","Viga","Unica One",
  "Calligraffitti","Pinyon Script","Gentium Basic","Cherry Cream Soda","Average",
  "Neucha","Nothing You Could Do","Fugaz One","Ubuntu Mono","Coda","Kalam",
  "Electrolize","Rancho","Share","Enriqueta","Basic","PT Mono","Chivo","Hanuman",
  "Julius Sans One","Carme","Syncopate","Allura","Allerta Stencil",
  "Chelsea Market","Kavivanar","Lusitana","Sarala","Michroma","Kameron",
  "Prata","Advent Pro","Galada","Allerta","Ceviche One","PT Serif Caption",
  "Just Another Hand","Bubblegum Sans","Marvel","Adamina","Spinnaker","Niconne",
  "Walter Turncoat","Freckle Face","Carter One","Nixie One","Pragati Narrow",
  "Doppio One","Cabin Sketch","Telex","Puritan","Schoolbell","Carrois Gothic",
  "Limelight","Marmelad","Parisienne","Reenie Beanie","Yantramanav","Sansita One",
  "Montserrat Alternates","Oxygen Mono","Marcellus","Alef","Press Start 2P",
  "Arbutus Slab","Overlock","Gochi Hand","Jockey One","Lustria","Merienda",
  "Crafty Girls","Contrail One","Aclonica","Port Lligat Slab",
  "Goudy Bookletter 1911","Radley","Yesteryear","Coustard","Waiting for the Sunrise",
  "Marcellus SC","Merienda One","Magra","Rochester","Berkshire Swash","Mate",
  "Grand Hotel","Corben","Belleza","Fontdiner Swanky","Six Caps",
  "Annie Use Your Telescope","Rosario","Halant","Oranienbaum","Alegreya SC",
  "Fredericka the Great","Quantico","Short Stack","Martel","Cousine","Cambay",
  "Anonymous Pro","Henny Penny","Italianno","Leckerli One","Racing Sans One",
  "Cutive Mono","Cinzel Decorative","Metrophobic","Fanwood Text","Assistant",
  "Duru Sans","Forum","Sree Krushnadevaraya","Pompiere","Mako","Sue Ellen Francisco",
  "Graduate","Ovo","Oleo Script Swash Caps","Miriam Libre","Tauri","Secular One",
  "Petit Formal Script","Gruppo","Gilda Display","Original Surfer","Mouse Memoirs",
  "Inder","Clicker Script","Caudex","Frijole","Allan","Quintessential","Lilita One",
  "Fira Mono","Tenor Sans","Slackey","Baumans","Zeyada","Wire One","Lemon","Mr Dafoe",
  "Alike","Capriola","Londrina Solid","Lateef","The Girl Next Door","Anaheim","Slabo 13px",
  "Unkempt","Brawler","Andika","Aladin","VT323","Quando","Crushed","NTR","Love Ya Like A Sister",
  "Bowlby One SC","Khmer","Kelly Slab","Poly","Palanquin","Delius","Give You Glory",
  "IM Fell DW Pica","Rufina","Oregano","Herr Von Muellerhoff","Judson","Caveat",
  "IM Fell English","IM Fell English SC","Prosto One","Happy Monkey","Finger Paint",
  "Bentham","Lekton","Stardos Stencil","Orienta","Strait","Fenix","UnifrakturMaguntia",
  "Itim","Just Me Again Down Here","Gafata","Headland One","La Belle Aurore",
  "Kotta One","Aref Ruqaa","Caesar Dressing","Karma","Expletus Sans","Andada",
  "Shanti","Skranji","Imprima","Qwigley","Timmana","Nova Square","Yeseva One",
  "Rationale","Arizonia","Shojumaru","Kranky","Sniglet","Belgrano","Fjord One",
  "Bilbo Swash Caps","GFS Didot","Lily Script One","Knewave","Holtwood One SC",
  "Ramaraja","Gabriela","Salsa","Carrois Gothic SC","Simonetta","Tienne","Megrim",
  "Loved by the King","Life Savers","Engagement","Stalemate","Geo","Norican",
  "Italiana","Dorsa","Martel Sans","Podkova","Kristi","Patrick Hand SC",
  "Dawning of a New Day","Mountains of Christmas","Delius Swash Caps","Share Tech",
  "Bowlby One","Federo","Codystar","Over the Rainbow","Amethysta","Vast Shadow",
  "Seaweed Script","Meddon","Averia Sans Libre","Mr De Haviland","Rammetto One",
  "Voces","Ramabhadra","Revalia","Averia Serif Libre","Ledger","Euphoria Script",
  "Fondamento","Cherry Swash","Share Tech Mono","Unna","Flamenco","Kite One",
  "Condiment","Sail","Biryani","Nova Mono","Cantora One","Rouge Script","Mallanna",
  "Buenard","Balthazar","IM Fell French Canon","Aguafina Script","Mate SC",
  "Cedarville Cursive","Raleway Dots","Maiden Orange","Cambo","IM Fell Double Pica",
  "McLaren","Rosarivo","Sofia","Englebert","Metamorphous","Rye","Medula One","Habibi",
  "Kadwa","Chicle","Titan One","Battambang","Coda Caption","Oldenburg","Artifika",
  "Chau Philomene One","Dynalight","Numans","Amarante","Milonga","Inika","Junge",
  "Stoke","IM Fell DW Pica SC","Wallpoet","Gurajada","Monofett","Prociono","Tulpen One",
  "Swanky and Moo Moo","Ruthie","Vibur","Scheherazade","Krona One","IM Fell Double Pica SC",
  "Stint Ultra Condensed","IM Fell Great Primer","Sancreek","Text Me One",
  "Wendy One","Averia Libre","Donegal One","Stint Ultra Expanded","IM Fell French Canon SC",
  "Sunshiney","Esteban","Kurale","Piedra","Offside","Iceland","Ruslan Display",
  "Delius Unicase","Ruluko","Buda","Angkor","IM Fell Great Primer SC","Overlock SC",
  "League Script","Chonburi","Paprika","Nokora","Linden Hill","Cagliostro","Sonsie One",
  "Snippet","Trade Winds","Nova Round","Montserrat Subrayada","Mrs Saint Delafield",
  "Suwannaphum","Ribeye","Akronim","Redressed","Port Lligat Sans","Mystery Quest",
  "Dr Sugiyama","Jaldi","Miniver","Bilbo","Irish Grover","Glass Antiqua","Elsie",
  "Sumana","Almendra","Mandali","Laila","Bigshot One","Della Respira","Antic Didone",
  "MedievalSharp","Suranna","Bubbler One","UnifrakturCook","New Rocker","Caveat Brush",
  "Jacques Francois","Nosifer","Sarpanch","Nova Slim","Germania One","Wellfleet",
  "Sarina","Pirata One","Peralta","Joti One","Rum Raisin","Julee","Emilys Candy",
  "Palanquin Dark","Keania One","Atomic Age","Griffy","Galindo","Nova Flat","Trykker",
  "Lovers Quarrel","Iceberg","Monsieur La Doulaise","Miltonian Tattoo","Kenia",
  "Croissant One","Diplomata","Astloch","Meie Script","Autour One","Petrona","Smythe",
  "Londrina Outline","Rozha One","Warnes","Chango","GFS Neohellenic","Galdeano",
  "Faster One","Ribeye Marrow","Spicy Rice","Fascinate","Bokor","Sriracha","Snowburst One",
  "Montaga","Modern Antiqua","Trochut","Londrina Sketch","Fresca","Vampiro One",
  "Eagle Lake","Content","Ranchers","Purple Purse","Sura","Londrina Shadow","Lancelot",
  "Averia Gruesa Libre","Passero One","Gorditas","Margarine","Jacques Francois Shadow",
  "Freehand","Asset","Devonshire","Jolly Lodger","Elsie Swash Caps","Sofadi One","Arya",
  "Macondo Swash Caps","Miltonian","Seymour One","Nova Cut","Felipa","Goblin One",
  "Bayon","Nova Script","Underdog","Preahvihear","Moul","Romanesco","Geostar Fill",
  "Sirin Stencil","Butterfly Kids","Metal Mania","Smokum","Rhodium Libre",
  "Mrs Sheppards","Koulen","Combo","Marko One","Princess Sofia","Aubrey","Molle",
  "Rubik Mono One","Miss Fajardose","Kdam Thmor","Spirax","Butcherman","Metal",
  "Bigelow Rules","Taprom","Federant","Gidugu","Geostar","Plaster","Dangrek",
  "Inknut Antiqua","Almendra Display","Emblema One","Asar","Bonbon","Siemreap","" +
  "Sahitya","Arbutus","Sevillana","Eater","Macondo","Supermercado One","Odor Mean Chey",
  "Amita","Erica One","Hanalei Fill","Almendra SC","Ranga","Mr Bedfort","Chenla",
  "Stalinist One","Dhurjati","Tenali Ramakrishna","Chela One","Diplomata SC",
  "Ruge Boogie","Kantumruy","Flavors","Jim Nightshade","Suravaram","Unlock","Modak",
  "Fascinate Inline","Moulpali","Fasthand","Ravi Prakash","Peddana","Hanalei"
] + ["Tisa"])
