"""empty message

Revision ID: 2a2a88617b3
Revises: c1506600798a
Create Date: 2016-05-20 17:24:35.303663

"""

# revision identifiers, used by Alembic.
revision = '2a2a88617b3'
down_revision = 'c1506600798a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('utm_source', sa.String(length=256), server_default="not-set", nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'utm_source')
    ### end Alembic commands ###
