"""empty message

Revision ID: 2fb67288380
Revises: 3a53f8cf6a6
Create Date: 2017-03-08 16:56:43.539988

"""

# revision identifiers, used by Alembic.
revision = '2fb67288380'
down_revision = '3a53f8cf6a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zapier_hook_endpoints', sa.Column('event', sa.String(length=128), nullable=False))
    op.add_column('zapier_hook_endpoints', sa.Column('target_url', sa.String(length=2048), nullable=False))
    op.drop_column('zapier_hook_endpoints', 'url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zapier_hook_endpoints', sa.Column('url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False))
    op.drop_column('zapier_hook_endpoints', 'target_url')
    op.drop_column('zapier_hook_endpoints', 'event')
    ### end Alembic commands ###
