"""empty message

Revision ID: 3a53f8cf6a6
Revises: 606dd6210987
Create Date: 2017-03-01 11:58:26.507638

"""

# revision identifiers, used by Alembic.
revision = '3a53f8cf6a6'
down_revision = '50366cf17fa0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zapier_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zapier_integrations_company_id'), 'zapier_integrations', ['company_id'], unique=False)
    op.create_table('zapier_trigger_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('post_event_log', postgresql.JSONB(), nullable=False),
    sa.Column('data', postgresql.JSONB(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zapier_trigger_events_company_id'), 'zapier_trigger_events', ['company_id'], unique=False)
    op.create_table('zapier_hook_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('zapier_integration_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zapier_integration_id'], ['zapier_integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zapier_hook_endpoints_company_id'), 'zapier_hook_endpoints', ['company_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zapier_hook_endpoints_company_id'), table_name='zapier_hook_endpoints')
    op.drop_table('zapier_hook_endpoints')
    op.drop_index(op.f('ix_zapier_trigger_events_company_id'), table_name='zapier_trigger_events')
    op.drop_table('zapier_trigger_events')
    op.drop_index(op.f('ix_zapier_integrations_company_id'), table_name='zapier_integrations')
    op.drop_table('zapier_integrations')
    ### end Alembic commands ###
