"""empty message

Revision ID: 3d8892a9d47
Revises: 1e9fc27c3d3
Create Date: 2016-06-15 17:52:47.893026

"""

# revision identifiers, used by Alembic.
revision = '3d8892a9d47'
down_revision = '1e9fc27c3d3'

from alembic import op
import sqlalchemy as sa
import app.models.users

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unsubscribed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', app.models.users.CIText(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unsubscribed')
    ### end Alembic commands ###
