"""chargebee

Revision ID: 3fdf58884628
Revises: 3a527ab0858a
Create Date: 2016-08-22 17:31:41.355005

"""

# revision identifiers, used by Alembic.
revision = '3fdf58884628'
down_revision = 'a85046f55b98'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chargebee_webhook_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('data', postgresql.JSONB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chargebee_subscription_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chargebee_subscription_cache_company_id'), 'chargebee_subscription_cache', ['company_id'], unique=False)
    op.drop_table('stripe_cards')
    op.drop_table('stripe_subscriptions')
    op.drop_table('stripe_customer')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_cards',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('address_city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_line1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_line1_check', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_line2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_zip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_zip_check', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cvc_check', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dynamic_last4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exp_month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exp_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('funding', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id_', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last4', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('object', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tokenization_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['stripe_customer.id'], name='stripe_cards_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stripe_cards_pkey')
    )
    op.create_table('stripe_subscriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plan', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cancel_at_period_end', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('canceled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('current_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('stripe_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('trial_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['stripe_customer.id'], name='stripe_subscriptions_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stripe_subscriptions_pkey')
    )
    op.create_table('stripe_customer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('stripe_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ip', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='stripe_customer_company_id_fkey'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='stripe_customer_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stripe_customer_pkey')
    )
    op.drop_index(op.f('ix_chargebee_subscription_cache_company_id'), table_name='chargebee_subscription_cache')
    op.drop_table('chargebee_subscription_cache')
    op.drop_table('chargebee_webhook_log')
    ### end Alembic commands ###
