"""email in shared proposal

Revision ID: 42e8c801cb70
Revises: 4a219263b02
Create Date: 2016-06-21 19:27:44.727888

"""

# revision identifiers, used by Alembic.
revision = '42e8c801cb70'
down_revision = '4a219263b02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_proposals', sa.Column('body', sa.String(length=5000), nullable=False, server_default=""))
    op.add_column('shared_proposals', sa.Column('from_name', sa.String(length=50), nullable=False, server_default=""))
    op.add_column('shared_proposals', sa.Column('subject', sa.String(length=300), nullable=False, server_default=""))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shared_proposals', 'subject')
    op.drop_column('shared_proposals', 'from_name')
    op.drop_column('shared_proposals', 'body')
    ### end Alembic commands ###
