"""empty message

Revision ID: 45057c95b6f0
Revises: 34d64b329da
Create Date: 2016-03-31 14:52:30.701512

"""

# revision identifiers, used by Alembic.
revision = '45057c95b6f0'
down_revision = '34d64b329da'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_city', sa.String(), nullable=True),
    sa.Column('address_country', sa.String(), nullable=True),
    sa.Column('address_line1', sa.String(), nullable=True),
    sa.Column('address_line1_check', sa.String(), nullable=True),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('address_state', sa.String(), nullable=True),
    sa.Column('address_zip', sa.String(), nullable=True),
    sa.Column('address_zip_check', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('cvc_check', sa.String(), nullable=False),
    sa.Column('dynamic_last4', sa.String(), nullable=True),
    sa.Column('exp_month', sa.Integer(), nullable=False),
    sa.Column('exp_year', sa.Integer(), nullable=False),
    sa.Column('funding', sa.String(), nullable=False),
    sa.Column('id_', sa.String(), nullable=False),
    sa.Column('last4', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('object', sa.String(), nullable=True),
    sa.Column('tokenization_method', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stripe_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('customer_json', postgresql.JSONB(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['stripe_cards.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_subscriptions')
    op.drop_table('stripe_cards')
    ### end Alembic commands ###
