"""empty message

Revision ID: 49cd951a84f
Revises: 2a2a88617b3
Create Date: 2016-05-24 17:37:43.334519

"""

# revision identifiers, used by Alembic.
revision = '49cd951a84f'
down_revision = '2a2a88617b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('welcome_email_sent', sa.Boolean(), server_default='true', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'welcome_email_sent')
    ### end Alembic commands ###
