"""empty message

Revision ID: 4a219263b02
Revises: 43fcecc2e20
Create Date: 2016-06-19 17:40:59.496094

"""

# revision identifiers, used by Alembic.
revision = '4a219263b02'
down_revision = '43fcecc2e20'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.models.users


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailjet_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', app.models.users.CIText(), nullable=False),
    sa.Column('json_response', postgresql.JSONB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mailjet_message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('json_response', postgresql.JSONB(), nullable=False),
    sa.Column('message_reason', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailjet_click_statistics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('json_response', postgresql.JSONB(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['mailjet_contact.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['mailjet_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailjet_open_information',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('json_response', postgresql.JSONB(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['mailjet_contact.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['mailjet_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailjet_open_information')
    op.drop_table('mailjet_click_statistics')
    op.drop_table('mailjet_message')
    op.drop_table('mailjet_contact')
    ### end Alembic commands ###
