"""empty message

Revision ID: 55f72855e70
Revises: 45057c95b6f0
Create Date: 2016-04-04 16:47:55.255384

"""

# revision identifiers, used by Alembic.
revision = '55f72855e70'
down_revision = '45057c95b6f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blocks_proposal_id'), 'blocks', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_clients_company_id'), 'clients', ['company_id'], unique=False)
    op.create_index(op.f('ix_comment_threads_block_uid'), 'comment_threads', ['block_uid'], unique=False)
    op.create_index(op.f('ix_comment_threads_proposal_id'), 'comment_threads', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_comments_thread_id'), 'comments', ['thread_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_import_section_search_company_id'), 'import_section_search', ['company_id'], unique=False)
    op.create_index(op.f('ix_proposal_last_seen_proposal_id'), 'proposal_last_seen', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_proposal_last_seen_user_id'), 'proposal_last_seen', ['user_id'], unique=False)
    op.create_index(op.f('ix_shared_blocks_shared_proposal_id'), 'shared_blocks', ['shared_proposal_id'], unique=False)
    op.create_index(op.f('ix_shared_comment_threads_block_id'), 'shared_comment_threads', ['block_id'], unique=False)
    op.create_index(op.f('ix_shared_comment_threads_shared_proposal_id'), 'shared_comment_threads', ['shared_proposal_id'], unique=False)
    op.create_index(op.f('ix_shared_comments_thread_id'), 'shared_comments', ['thread_id'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_card_id'), 'stripe_subscriptions', ['card_id'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_company_id'), 'stripe_subscriptions', ['company_id'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_created_by_id'), 'stripe_subscriptions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_index(op.f('ix_stripe_subscriptions_created_by_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_company_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_card_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_shared_comments_thread_id'), table_name='shared_comments')
    op.drop_index(op.f('ix_shared_comment_threads_shared_proposal_id'), table_name='shared_comment_threads')
    op.drop_index(op.f('ix_shared_comment_threads_block_id'), table_name='shared_comment_threads')
    op.drop_index(op.f('ix_shared_blocks_shared_proposal_id'), table_name='shared_blocks')
    op.drop_index(op.f('ix_proposal_last_seen_user_id'), table_name='proposal_last_seen')
    op.drop_index(op.f('ix_proposal_last_seen_proposal_id'), table_name='proposal_last_seen')
    op.drop_index(op.f('ix_import_section_search_company_id'), table_name='import_section_search')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_thread_id'), table_name='comments')
    op.drop_index(op.f('ix_comment_threads_proposal_id'), table_name='comment_threads')
    op.drop_index(op.f('ix_comment_threads_block_uid'), table_name='comment_threads')
    op.drop_index(op.f('ix_clients_company_id'), table_name='clients')
    op.drop_index(op.f('ix_blocks_proposal_id'), table_name='blocks')
    ### end Alembic commands ###
