"""Oauth stripe fields

Revision ID: 606dd6210987
Revises: a43832e75ccd
Create Date: 2017-02-15 11:40:48.098938

"""

# revision identifiers, used by Alembic.
revision = '606dd6210987'
down_revision = 'a43832e75ccd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe_integrations', sa.Column('access_token', sa.String(length=512), nullable=False))
    op.add_column('stripe_integrations', sa.Column('livemode', sa.Boolean(), nullable=True))
    op.add_column('stripe_integrations', sa.Column('refresh_token', sa.String(length=512), nullable=False))
    op.add_column('stripe_integrations', sa.Column('scope', sa.String(length=50), nullable=False))
    op.add_column('stripe_integrations', sa.Column('stripe_publishable_key', sa.String(length=512), nullable=False))
    op.add_column('stripe_integrations', sa.Column('stripe_user_id', sa.String(length=512), nullable=False))
    op.add_column('stripe_integrations', sa.Column('token_type', sa.String(length=50), nullable=False))
    op.drop_column('stripe_integrations', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe_integrations', sa.Column('token', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_column('stripe_integrations', 'token_type')
    op.drop_column('stripe_integrations', 'stripe_user_id')
    op.drop_column('stripe_integrations', 'stripe_publishable_key')
    op.drop_column('stripe_integrations', 'scope')
    op.drop_column('stripe_integrations', 'refresh_token')
    op.drop_column('stripe_integrations', 'livemode')
    op.drop_column('stripe_integrations', 'access_token')
    # ### end Alembic commands ###
