"""onboarding

Revision ID: 8c2d981a31e0
Revises: 3b86a1f1fa35
Create Date: 2016-04-11 12:28:30.826368

"""

# revision identifiers, used by Alembic.
revision = '8c2d981a31e0'
down_revision = '3b86a1f1fa35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarded', sa.Boolean(), nullable=False, server_default="False"))
    op.alter_column('users', 'disabled', server_default=None)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarded')
    ### end Alembic commands ###
