"""move to es

Revision ID: a85046f55b98
Revises: 3a527ab0858a
Create Date: 2016-08-21 18:19:07.502303

"""

# revision identifiers, used by Alembic.
revision = 'a85046f55b98'
down_revision = '3a527ab0858a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_section_search')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_section_search',
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('section_uid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('proposal_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ts_title', postgresql.TSVECTOR(), autoincrement=False, nullable=False),
    sa.Column('client', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('all_content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ts_all_content', postgresql.TSVECTOR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='import_section_search_company_id_fkey'),
    sa.ForeignKeyConstraint(['section_uid'], ['blocks.uid'], name='import_section_search_section_uid_fkey', ondelete='CASCADE', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('section_uid', name='import_section_search_pkey')
    )
    ### end Alembic commands ###
