"""more stripe

Revision ID: c1506600798a
Revises: 8c2d981a31e0
Create Date: 2016-04-13 19:23:59.479369

"""

# revision identifiers, used by Alembic.
revision = 'c1506600798a'
down_revision = '8c2d981a31e0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_id', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_customer_company_id'), 'stripe_customer', ['company_id'], unique=False)
    op.create_index(op.f('ix_stripe_customer_created_by_id'), 'stripe_customer', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_stripe_customer_stripe_id'), 'stripe_customer', ['stripe_id'], unique=False)
    op.add_column('stripe_cards', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_stripe_cards_customer_id'), 'stripe_cards', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'stripe_cards', 'stripe_customer', ['customer_id'], ['id'])
    op.add_column('stripe_subscriptions', sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False))
    op.add_column('stripe_subscriptions', sa.Column('canceled_at', sa.DateTime(), nullable=True))
    op.add_column('stripe_subscriptions', sa.Column('current_period_end', sa.DateTime(), nullable=False))
    op.add_column('stripe_subscriptions', sa.Column('current_period_start', sa.DateTime(), nullable=False))
    op.add_column('stripe_subscriptions', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('stripe_subscriptions', sa.Column('ended_at', sa.DateTime(), nullable=True))
    op.add_column('stripe_subscriptions', sa.Column('status', sa.String(length=200), nullable=False))
    op.add_column('stripe_subscriptions', sa.Column('stripe_id', sa.String(length=50), nullable=False))
    op.add_column('stripe_subscriptions', sa.Column('trial_end', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_stripe_subscriptions_customer_id'), 'stripe_subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_stripe_id'), 'stripe_subscriptions', ['stripe_id'], unique=False)
    op.drop_index('ix_stripe_subscriptions_card_id', table_name='stripe_subscriptions')
    op.drop_index('ix_stripe_subscriptions_company_id', table_name='stripe_subscriptions')
    op.drop_index('ix_stripe_subscriptions_created_by_id', table_name='stripe_subscriptions')
    op.drop_constraint('stripe_subscriptions_card_id_fkey', 'stripe_subscriptions', type_='foreignkey')
    op.drop_constraint('stripe_subscriptions_created_by_id_fkey', 'stripe_subscriptions', type_='foreignkey')
    op.drop_constraint('stripe_subscriptions_company_id_fkey', 'stripe_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'stripe_subscriptions', 'stripe_customer', ['customer_id'], ['id'])
    op.drop_column('stripe_subscriptions', 'customer_json')
    op.drop_column('stripe_subscriptions', 'created_by_id')
    op.drop_column('stripe_subscriptions', 'card_id')
    op.drop_column('stripe_subscriptions', 'company_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe_subscriptions', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stripe_subscriptions', sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stripe_subscriptions', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stripe_subscriptions', sa.Column('customer_json', postgresql.JSONB(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stripe_subscriptions', type_='foreignkey')
    op.create_foreign_key('stripe_subscriptions_company_id_fkey', 'stripe_subscriptions', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('stripe_subscriptions_created_by_id_fkey', 'stripe_subscriptions', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key('stripe_subscriptions_card_id_fkey', 'stripe_subscriptions', 'stripe_cards', ['card_id'], ['id'])
    op.create_index('ix_stripe_subscriptions_created_by_id', 'stripe_subscriptions', ['created_by_id'], unique=False)
    op.create_index('ix_stripe_subscriptions_company_id', 'stripe_subscriptions', ['company_id'], unique=False)
    op.create_index('ix_stripe_subscriptions_card_id', 'stripe_subscriptions', ['card_id'], unique=False)
    op.drop_index(op.f('ix_stripe_subscriptions_stripe_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_customer_id'), table_name='stripe_subscriptions')
    op.drop_column('stripe_subscriptions', 'trial_end')
    op.drop_column('stripe_subscriptions', 'stripe_id')
    op.drop_column('stripe_subscriptions', 'status')
    op.drop_column('stripe_subscriptions', 'ended_at')
    op.drop_column('stripe_subscriptions', 'customer_id')
    op.drop_column('stripe_subscriptions', 'current_period_start')
    op.drop_column('stripe_subscriptions', 'current_period_end')
    op.drop_column('stripe_subscriptions', 'canceled_at')
    op.drop_column('stripe_subscriptions', 'cancel_at_period_end')
    op.drop_constraint(None, 'stripe_cards', type_='foreignkey')
    op.drop_index(op.f('ix_stripe_cards_customer_id'), table_name='stripe_cards')
    op.drop_column('stripe_cards', 'customer_id')
    op.drop_index(op.f('ix_stripe_customer_stripe_id'), table_name='stripe_customer')
    op.drop_index(op.f('ix_stripe_customer_created_by_id'), table_name='stripe_customer')
    op.drop_index(op.f('ix_stripe_customer_company_id'), table_name='stripe_customer')
    op.drop_table('stripe_customer')
    ### end Alembic commands ###
