"""signature

Revision ID: c623c7b1fc22
Revises: 4fac9c1bc52
Create Date: 2016-06-28 17:04:10.334980

"""

# revision identifiers, used by Alembic.
revision = 'c623c7b1fc22'
down_revision = '4fac9c1bc52'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shared_proposal_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('document', postgresql.JSONB, nullable=False),
    sa.Column('keyczar_signature', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.ForeignKeyConstraint(['shared_proposal_id'], ['shared_proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signatures_proposal_id'), 'signatures', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_signatures_shared_proposal_id'), 'signatures', ['shared_proposal_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signatures_shared_proposal_id'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_proposal_id'), table_name='signatures')
    op.drop_table('signatures')
    ### end Alembic commands ###
