"""add source to client

Revision ID: df334b758549
Revises: ef7d5195ae7d
Create Date: 2016-11-26 11:38:54.483139

"""

# revision identifiers, used by Alembic.
revision = 'df334b758549'
down_revision = 'ef7d5195ae7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('source', sa.String(length=64), server_default="", nullable=False))
    op.add_column('clients', sa.Column('source_id', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'source')
    ### end Alembic commands ###
