"""slack integration

Revision ID: e77bb317b569
Revises: f12eff482d6f
Create Date: 2016-11-19 19:17:08.562946

"""

# revision identifiers, used by Alembic.
revision = 'e77bb317b569'
down_revision = '4bf5848287c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('team_name', sa.String(length=512), nullable=False),
    sa.Column('channel', sa.String(length=512), nullable=False),
    sa.Column('webhook_url', sa.String(length=512), nullable=False),
    sa.Column('post_on_view', sa.Boolean(), nullable=True),
    sa.Column('post_on_comment', sa.Boolean(), nullable=True),
    sa.Column('post_on_signature', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_integrations_company_id'), 'slack_integrations', ['company_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slack_integrations_company_id'), table_name='slack_integrations')
    op.drop_table('slack_integrations')
    ### end Alembic commands ###
