"""trial end emails

Revision ID: f12eff482d6f
Revises: f24ebb12082d
Create Date: 2016-10-24 16:23:24.282231

"""

# revision identifiers, used by Alembic.
revision = 'f12eff482d6f'
down_revision = 'f24ebb12082d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trial_end_email_sent', sa.Boolean(), nullable=False, server_default="False"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_end_email_sent')
    ### end Alembic commands ###
