"""analytics

Revision ID: f24ebb12082d
Revises: 3fdf58884628
Create Date: 2016-10-05 18:18:40.584851

"""

# revision identifiers, used by Alembic.
revision = 'f24ebb12082d'
down_revision = '3fdf58884628'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_proposals_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uid', postgresql.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('data', postgresql.JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('shared_proposal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shared_proposal_id'], ['shared_proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_proposals_events_shared_proposal_id'), 'shared_proposals_events', ['shared_proposal_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_proposals_events_shared_proposal_id'), table_name='shared_proposals_events')
    op.drop_table('shared_proposals_events')
    ### end Alembic commands ###
